### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by AkiMosi** [ubermachine/NseBhavCopy-Fetcher-Node#1]
Could you please a step by step working example, please?

**Comment by ubermachine** [comment]
Oh i thought it was self explanatory you might have difficulty understanding how to run it as you are new to node.
INSTALL node 
make a folder
run
 `npm init`
create a file named 
index.js in it
then follow readme after installing module copy from usage in readme
then run 
node index.js

**Comment by AkiMosi** [comment]
Thanks for the guide, will try and get back to you.!
